services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "6969:80"  # pgAdmin will be available on localhost:8080
    depends_on:
      - postgres  # Ensure PostgreSQL is ready before starting pgAdmin
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
